In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


## Creating an array of 10 elements

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,0])

In [4]:
print(a)

[1 2 3 4 5 6 7 8 9 0]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
##Create a numpy array of size 10, filled with zeros.¶


In [8]:
z=np.zeros(10)

In [9]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
##Create a numpy array with values ranging from 10 to 49¶


In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
## Create a numpy matrix of 2*2 integers, filled with ones.¶


In [17]:
np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

In [16]:
##Create a numpy matrix of 3*2 float numbers, filled with ones.


In [18]:
np.ones([3,2],dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
##Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.


In [22]:
X = np.arange(4,dtype=np.float)

np.ones_like(X)

array([1., 1., 1., 1.])

In [ ]:
##Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.


In [23]:
X = np.arange(4,dtype=np.float)

np.zeros_like(X)

array([0., 0., 0., 0.])

In [24]:
## Create a numpy matrix of 4*4 integers, filled with fives.¶


In [27]:
np.ones([4,4], dtype=np.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# we created an array with 4 elements but then we nulify the whole matrix and add +7 with each element


In [33]:
X= np.array([[2,2], [6,2]], dtype=np.int)

np.zeros_like(X) + 7

array([[7, 7],
       [7, 7]])

In [ ]:
## Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.¶


In [35]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
## Create a numpy array, filled with 8 random integer values between 1 and 10.¶


In [39]:
np.random.randint(10, size=8)


array([6, 0, 0, 3, 2, 1, 4, 8])

In [40]:
#Create a 3*3*3 numpy matrix, filled with random float values.¶


In [43]:
np.random.randn(3,3,3)

array([[[-1.52227746, -0.34113245, -1.46467048],
        [-1.12241295, -0.75453932, -0.6580008 ],
        [ 0.49006613,  1.01492772,  0.53976258]],

       [[-0.15853816,  0.71430288, -0.32772289],
        [-0.11472243,  1.36878744,  1.29358275],
        [-0.07487616, -0.05327547,  1.26065391]],

       [[-1.77649544,  0.34002153,  0.73224252],
        [ 0.18550003,  0.11069844, -0.50333561],
        [-0.12257367,  0.35843548, -0.33215337]]])

In [44]:
## Given the X python list convert it to an Y numpy array¶




In [45]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [46]:
## Given the X numpy array, make a copy and store it on Y.¶



In [47]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 4578772112
[5 2 3] 4578784560


In [48]:
np.arange(1, 11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.arange(1, 11, 2)
#alternate numbers

array([1, 3, 5, 7, 9])

In [51]:
np.arange(1, 11)[::-1]
## display 1-11 in descending order

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [62]:
x=np.random.randint(0,9, size=9)
x.reshape(3,3)


#3x3 matrix and display random numbers 0-9 

array([[1, 0, 1],
       [1, 5, 2],
       [2, 8, 0]])

In [68]:
Z = np.zeros((10,10)) ## use double brackets

print("%d bytes" % (Z.size * Z.itemsize))


800 bytes


In [75]:
np.zeros((10,10)) ## use double brackets

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

In [77]:
X[2]

'C'

In [79]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

In [87]:
i=np.arange(3,10)

In [84]:
print(i)


[3 4 5 6 7 8 9]


In [88]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [89]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [90]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [92]:
   X = np.array([
 [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [93]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]


array([13, 14, 15, 16])

In [94]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

In [95]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

In [96]:
##Given the X numpy matrix, show the middle row elements¶

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [97]:
##Given the X numpy matrix, show the first two elements on the first two rows¶


X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

In [98]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)
#convert array into integer


array([-5., -3.,  0., 10., 40.])

In [99]:
X = [-5, -3, 0, 10, 40]

X[::-1]

#Reverse the given numpy array (first element becomes last)

[40, 10, 0, -3, -5]

In [102]:
X = [0, 10, -5, 40, -3]

X.sort()
print(X)

#sorting

[-5, -3, 0, 10, 40]


In [103]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X
#swap


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [105]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X
#Given the X numpy matrix, change the last item on the last row with a 0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [106]:
X=np.array([  
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

#add 5 to each element in the element

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [107]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

#boolean is also called mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [108]:

X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]


#above same query but different display code line

array([-1,  0, -4,  0,  0, -9])

In [109]:

X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

In [110]:

X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

#Given the X numpy array, get numbers higher than the elements mean

array([ 2,  5,  6, 10])

In [114]:
#Given the X numpy array, get numbers equal to 2 or 10¶

X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
#to get true or false just write mask

X[mask]

array([ 2, 10])

In [116]:
#Given the X numpy array, return True if none of its elements is zero

X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

In [118]:
# Given the X numpy array, return True if any of its elements is zero

X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

In [119]:
#Given the X numpy array, show the sum of its elements¶

X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

In [121]:
#Given the X numpy array, show the mean value of its elements¶


X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

In [124]:
#Given the X numpy matrix, show the sum of its columns¶

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

array([28, 32, 36, 40])

In [125]:
#Given the X numpy matrix, show the mean value of its rows

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) 

array([ 2.5,  6.5, 10.5, 14.5])

In [126]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10